# Motor control message
uint64 timestamp			# time since system start (microseconds)
uint64 timestamp_sample	    # the timestamp the data this control response is based on was sampled

float32 u1
float32 u2
float32 u3
float32 f1
float32 f2
float32 f3
float32 fsum
float32 alt_error
float32 q_r
float32 q_i
float32 q_j
float32 q_k
float32 p_s
float32 q_s
float32 r_s
float32 n_x
float32 n_y
float32 n_z
float32 nx_aor
float32 ny_aor
float32 nz_aor
float32 roll_rad
float32 pitch_rad
float32 yaw_rad
float32 x
float32 y
float32 z




# timestamp,u1,u2,f1,f2,f3,p_s,q_s,r_s,n_x,n_y,n_z,roll_rad,pitch_rad,yaw_rad,x,y,z
